# Generated by Django 3.2.8 on 2021-10-27 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ramos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('prioridad', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=10, message='Ingrese una prioridad válida'), django.core.validators.MinValueValidator(limit_value=1, message='Ingrese una prioridad válida')])),
                ('color', models.CharField(choices=[('#b52218', 'Rojo'), ('#2735f2', 'Azul'), ('#1c731e', 'Verde'), ('#1c731e', 'Amarillo'), ('#8237ad', 'Morado'), ('#ed55c0', 'Rosa'), ('#ed7700', 'Anaranjado'), ('#2f8a73', 'Turquesa')], default='#b52218', max_length=15)),
            ],
        ),
    ]
