# Generated by Django 3.2.8 on 2021-10-27 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ramos',
            new_name='Ramos_y_preferencias',
        ),
    ]
