# Generated by Django 3.2.8 on 2021-12-03 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('randp', '0002_rename_ramos_ramos_y_preferencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramos_y_preferencias',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
