# Generated by Django 3.2.9 on 2021-12-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randp', '0003_ramos_y_preferencias_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eliminar_ramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramo_id', models.IntegerField()),
            ],
        ),
    ]
