# Generated by Django 3.2.9 on 2021-12-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='ramo',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
