# Generated by Django 3.2.9 on 2021-12-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_calendario', '0002_eventos_ramo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='prioridad',
            field=models.IntegerField(default=1),
        ),
    ]
