# Generated by Django 3.2.9 on 2021-12-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_calendario', '0002_eventos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='ramo',
            field=models.CharField(default='Lenguaje', max_length=120),
        ),
    ]
