# Generated by Django 3.2.9 on 2021-12-03 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_calendario', '0003_alter_eventos_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='prioridad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10, message='Debe ingresar una prioridad dentro del rango (1-10)'), django.core.validators.MinValueValidator(1, message='Debe ingresar una prioridad dentro del rango (1-10)')]),
        ),
    ]
